AWSTemplateFormatVersion: '2010-09-09'
Description: S3 bucket with versioning and bucket owner enforced object ownership

Parameters:
  S3BucketName:
    Type: String
    Description: S3 bucket name

Resources:
  TerraformStateBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub ${S3BucketName}
      VersioningConfiguration:
        Status: Enabled
      OwnershipControls:
        Rules:
          - ObjectOwnership: BucketOwnerEnforced
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

Outputs:
  BucketName:
    Description: The name of the created S3 bucket
    Value: !Ref TerraformStateBucket

  BucketArn:
    Description: The ARN of the created S3 bucket
    Value: !GetAtt TerraformStateBucket.Arn